services:
  web:
    build: .
    ports:
      - "8080:80"
    container_name: mycontainer
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - mynetwork

  db:
    image: mysql:8
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: myapp
    networks:
      - mynetwork

  registry:
    image: registry:2
    container_name: myregistry
    ports:
      - "5000:5000"
    volumes:
      - ./registry-data:/var/lib/registry
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
